version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example1
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - mysql
    ports:
      - "5173:5173"
  
  nginx:
    image: nginx:alpine
    container_name: nginx-example1
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql-example1
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: larapavue-test
      MYSQL_USER: larapavue-test
      MYSQL_PASSWORD: larapavue-test
    ports:
      - '3337:3306'
    expose:
      - 3306
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data: